### ISSUE TITLE
3rd example error

### ISSUE THREAD

**Issue by mcomsa** [migariane/weltmle#1]
Hi,
Thank you for your ado. I tried to run your examples and I encountered an error related to the third one.
The syntax:
use http://www.stata-press.com/data/r14/cattaneo2.dta
preserve
eltmle bweight mbsmoke mage medu prenatal mmarried, tmleglsrf
restore

The error:
end of do-file
file data2.dta not found
r(601);

The first two examples worked. What I have done wrong at the 3rd one? Any ideas?

Thank you!
Mircea

**Comment by migariane** [comment]
Dear Mircea,
Thank you for your note.
Please, try to install the following packages in your R setting:
install.packages("foreign","SuperLearner","glmnet","randomForest")
Hope it will work.
Best regards,
Miguel Angel

**Comment by mcomsa** [comment]
Dear Miguel Angel,
Thank you for your answer. I have checked and all R packages mentioned are installed. It must be something else. I tried to run it on another PC and I received the same error. Any other ideas?
All the best!
Mircea

**Comment by migariane** [comment]
Dear Mircea,
I've run the example in my computer (MAC), and it is ok (4 cores and 16 GB ran memory). 
Notice that Lasso and Random Forest estimation in R is time-consuming and requires a huge quantity of memory RAN. Given that the other two examples you executed were OK, it might be that for the third example you had some memory issues running R and the program did not generate the data2.dta needed to run eltmle.
In any case, try it again:
.**cd Desktop**
.use http://www.stata-press.com/data/r14/cattaneo2.dta
.preserve
.eltmle bweight mbsmoke mage medu prenatal mmarried, tmleglsrf
.restore
Also, remember: 
Remember 1: You must change your working directory to the location of the Stata.dta file.
Remember 2: Mac users must have installed R software on their personal computer as eltmle calls R to implement the Super Learner. The R executable file must be located at the following path: "/usr/local/bin/r".
Remember 3: Windows users must have installed R software on their personal computer as eltmle calls R to implement the Super Learner. The R executable file must be located at the following path: "C:\ProgramFiles\R\R-X.X.X\bin\x64\R.exe" (where X stands for the number of the version)                                         Remember 4: Windows users must have only one version of R software installed on their personal computer at the following path: "C:\Program Files\R\R-X.X.X\bin\x64\R.exe". In case more than one different version is located in the above-highlighted path users would like to keep the latest.
Remember 5: In case you want to preserve the original dataset you can use the preserve/restore Stata functionality in combination to the Stata eltmle command as shown in the previous example.
Thank you,
Kind regards,
MA

**Comment by akhtarsd678** [comment]
Hi Angel,
Please guide me Stata becomes unresponsive after this. I have done all that you describe above.
Thanks/ SA
[Issue in running the example data.docx](https://github.com/user-attachments/files/16321878/Issue.in.runing.the.example.data.docx)
